title: Korri's Lab
description: Terminal-built security tools & research
theme: minima
markdown: kramdown

minima:
  skin: dark
  custom_css:
    - assets/style.css

header_pages:
  - index.md
  - projects.md
  - scripts.md
  - writeups.md
  - about.md
